# fly.toml app configuration file generated for blue-wood-2896 on 2023-04-27T22:03:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blue-wood-2896"
primary_region = "yyz"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
